"""rename department

Revision ID: 6b6885a74cd5
Revises: c29825c032d0
Create Date: 2024-06-26 09:53:35.972414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6885a74cd5'
down_revision = 'c29825c032d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('department', 'departments')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('departments', 'department')
    # ### end Alembic commands ###
